### ISSUE TITLE
Need tables to be styled in the pattern library

### ISSUE THREAD

**Issue by johnkealy** [ucsf-web-services/ucsf_pattern_library#5]
Tables exist, but they haven't got any UCSF style.
http://webpatterns.ucsf.edu/?p=atoms-tables

**Comment by eguerin-ucsf** [comment]
We should make this a priority as we need table styling back in  StarterKit and we need something that will at least work in a responsive way for some of the use-cases.

**Comment by jaysonjaynes** [comment]
I was just writing up another issue to make them responsive. I believe we will need a few solutions to responsive tables depending on the content and use case, i.e. table headers vs table column vs table header and column used for data comparisons.
