### ISSUE TITLE
express the development roadmap as github issues

### ISSUE THREAD

**Issue by andrewmallis** [ucsf-web-services/ucsf_pattern_library#6]
For transparency into the features being developed by webservices, and so we can better coordinate our work as a community, it would be useful to have a complete issue queue in github.

We can also discuss features and contribute to them in development here, so we aren't reinventing the wheel.

Suggest using labels to help express requests vs issues being worked on by others.

Milestones can also be used to express the roadmap.

**Comment by McKristian** [comment]
you may want to take me off this thread.

**Comment by jaysonjaynes** [comment]
Andrew, like I said yesterday, we are planning on moving our future developments into the issues queue here on GitHub but haven't had the chance, yet. I'll make sure to move them over next week so we can have complete transparency. That's a great idea to use labels and milestones. Really looking forward to collaborating!

Kristian, you are not a member or collaborator on this repository, but you are watching it. To not receive notifications, you have to unwatch this repository. Here's a link that instructs how to do that: https://help.github.com/articles/watching-and-unwatching-repositories/

**Comment by jaysonjaynes** [comment]
Hey Andrew, I've add what's on our list for improvements in Issues now. I added the bigger efforts as Milestones. Please feel free to add, comment, etc.
